import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author x16399856
 */
//CONNOR, LAUREN, JAKE
public class FlightGUI extends javax.swing.JFrame {

    Plane p;
    Plane log[];
    int size;
    int mainPrice;
    int secPPrice;
    int secJPrice;
    int finalPrice;

    /**
     * Creates new form FlightGUI
     */
    public FlightGUI() {
        initComponents();
        
        /*
        JFrame temp = new JFrame();
        temp.pack();
        Insets insets = temp.getInsets();
        temp = null;
        this.setSize(new Dimension(insets.left + insets.right + 1120,
                insets.top + insets.bottom + 600));
        this.setVisible(true);
        this.setResizable(false);
        */

        
        planeLbl.setVisible(false);
        ticketTypeLbl.setVisible(false);
        ticketTypeCB.setVisible(false);
        moviesLbl.setVisible(false);
        movieCB.setVisible(false);
        wifiLbl.setVisible(false);
        wifiCB.setVisible(false);
   

        jetLbl.setVisible(false);
        packageDealLbl.setVisible(false);
        packageDealCB.setVisible(false);
        entertainmentLbl.setVisible(false);
        entCB.setVisible(false);        
        massageLbl.setVisible(false);
        massageCB.setVisible(false);
        

        priceDisplayedLbl.setVisible(false);
        finalPriceLbl.setVisible(false);

        log = new Plane[100];
        size= 0 ;
        ReadFile();
    }
    
    //Lauren
    public void writeToFile(){
        try{
            File f = new File("output.data");
            FileOutputStream fStream = new FileOutputStream(f);
            ObjectOutputStream oStream = new ObjectOutputStream(fStream);
            oStream.writeObject(log);
            oStream.close();
        }
        catch(IOException ex){
            System.out.println(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // Connor
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        movieBG = new javax.swing.ButtonGroup();
        wifiBG = new javax.swing.ButtonGroup();
        entertainmentBG = new javax.swing.ButtonGroup();
        massageBG = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        titleLbl = new javax.swing.JLabel();
        airlineCB = new javax.swing.JComboBox<>();
        flightTypeCB = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        planeLbl = new javax.swing.JLabel();
        jetLbl = new javax.swing.JLabel();
        ticketTypeLbl = new javax.swing.JLabel();
        ticketTypeCB = new javax.swing.JComboBox<>();
        moviesLbl = new javax.swing.JLabel();
        wifiLbl = new javax.swing.JLabel();
        packageDealLbl = new javax.swing.JLabel();
        packageDealCB = new javax.swing.JComboBox<>();
        entertainmentLbl = new javax.swing.JLabel();
        massageLbl = new javax.swing.JLabel();
        priceBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        clearFormBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        airlineLbl = new javax.swing.JLabel();
        priceDisplayedLbl = new javax.swing.JLabel();
        finalPriceLbl = new javax.swing.JLabel();
        destinationLbl = new javax.swing.JLabel();
        flightTypeLbl = new javax.swing.JLabel();
        destinationCB = new javax.swing.JComboBox<>();
        movieCB = new javax.swing.JComboBox<>();
        entCB = new javax.swing.JComboBox<>();
        wifiCB = new javax.swing.JComboBox<>();
        massageCB = new javax.swing.JComboBox<>();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 0, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        titleLbl.setBackground(new java.awt.Color(255, 255, 255));
        titleLbl.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(255, 255, 255));
        titleLbl.setText("myFlight.com");
        getContentPane().add(titleLbl);
        titleLbl.setBounds(196, 4, 338, 29);

        airlineCB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        airlineCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Ryanair", "Aer Lingus", "Virgin Atlantic", "CityJet" }));
        airlineCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineCBActionPerformed(evt);
            }
        });
        getContentPane().add(airlineCB);
        airlineCB.setBounds(228, 44, 123, 21);

        flightTypeCB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        flightTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Plane", "Jet" }));
        flightTypeCB.setSelectedItem(0);
        flightTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightTypeCBActionPerformed(evt);
            }
        });
        getContentPane().add(flightTypeCB);
        flightTypeCB.setBounds(228, 122, 123, 21);

        jSeparator1.setBackground(new java.awt.Color(0, 204, 255));
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 157, 544, 10);

        jSeparator3.setBackground(new java.awt.Color(0, 204, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(244, 173, 22, 220);

        planeLbl.setBackground(new java.awt.Color(0, 204, 255));
        planeLbl.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        planeLbl.setForeground(new java.awt.Color(255, 255, 255));
        planeLbl.setText("Plane");
        getContentPane().add(planeLbl);
        planeLbl.setBounds(105, 173, 49, 24);

        jetLbl.setBackground(new java.awt.Color(0, 204, 255));
        jetLbl.setFont(new java.awt.Font("Calibri", 2, 16)); // NOI18N
        jetLbl.setForeground(new java.awt.Color(255, 255, 255));
        jetLbl.setText("Jet");
        getContentPane().add(jetLbl);
        jetLbl.setBounds(358, 173, 45, 23);

        ticketTypeLbl.setBackground(new java.awt.Color(0, 204, 255));
        ticketTypeLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        ticketTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        ticketTypeLbl.setText("Ticket Type:");
        getContentPane().add(ticketTypeLbl);
        ticketTypeLbl.setBounds(21, 209, 78, 26);

        ticketTypeCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coach", "First Class" }));
        ticketTypeCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketTypeCBActionPerformed(evt);
            }
        });
        getContentPane().add(ticketTypeCB);
        ticketTypeCB.setBounds(135, 212, 100, 20);

        moviesLbl.setBackground(new java.awt.Color(0, 204, 255));
        moviesLbl.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        moviesLbl.setForeground(new java.awt.Color(255, 255, 255));
        moviesLbl.setText("In-Flight Movies:");
        getContentPane().add(moviesLbl);
        moviesLbl.setBounds(21, 254, 112, 27);

        wifiLbl.setBackground(new java.awt.Color(0, 204, 255));
        wifiLbl.setFont(new java.awt.Font("Candara", 0, 16)); // NOI18N
        wifiLbl.setForeground(new java.awt.Color(255, 255, 255));
        wifiLbl.setText("Wifi:");
        getContentPane().add(wifiLbl);
        wifiLbl.setBounds(21, 326, 50, 25);

        packageDealLbl.setBackground(new java.awt.Color(0, 204, 255));
        packageDealLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        packageDealLbl.setForeground(new java.awt.Color(255, 255, 255));
        packageDealLbl.setText("Package Deal:");
        getContentPane().add(packageDealLbl);
        packageDealLbl.setBounds(270, 217, 92, 20);

        packageDealCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Premium" }));
        getContentPane().add(packageDealCB);
        packageDealCB.setBounds(454, 217, 80, 20);

        entertainmentLbl.setBackground(new java.awt.Color(0, 204, 255));
        entertainmentLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        entertainmentLbl.setForeground(new java.awt.Color(255, 255, 255));
        entertainmentLbl.setText("In-Flight Entertainment:");
        getContentPane().add(entertainmentLbl);
        entertainmentLbl.setBounds(270, 265, 160, 20);

        massageLbl.setBackground(new java.awt.Color(0, 204, 255));
        massageLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        massageLbl.setForeground(new java.awt.Color(255, 255, 255));
        massageLbl.setText("Massage:");
        getContentPane().add(massageLbl);
        massageLbl.setBounds(270, 333, 63, 20);

        priceBtn.setBackground(new java.awt.Color(255, 255, 255));
        priceBtn.setText("Check Price");
        priceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceBtnActionPerformed(evt);
            }
        });
        getContentPane().add(priceBtn);
        priceBtn.setBounds(288, 426, 110, 23);

        addBtn.setBackground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addBtn);
        addBtn.setBounds(37, 426, 70, 23);

        displayBtn.setBackground(new java.awt.Color(255, 255, 255));
        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        getContentPane().add(displayBtn);
        displayBtn.setBounds(162, 426, 80, 23);

        clearFormBtn.setBackground(new java.awt.Color(255, 255, 255));
        clearFormBtn.setText("Clear Form");
        clearFormBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormBtnActionPerformed(evt);
            }
        });
        getContentPane().add(clearFormBtn);
        clearFormBtn.setBounds(423, 426, 110, 23);

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn);
        searchBtn.setBounds(413, 76, 90, 23);

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jPanel2ComponentRemoved(evt);
            }
        });
        jPanel2.setLayout(null);

        airlineLbl.setBackground(new java.awt.Color(0, 204, 255));
        airlineLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        airlineLbl.setForeground(new java.awt.Color(255, 255, 255));
        airlineLbl.setText("Airline:");
        jPanel2.add(airlineLbl);
        airlineLbl.setBounds(140, 40, 79, 20);

        priceDisplayedLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        priceDisplayedLbl.setForeground(new java.awt.Color(255, 255, 255));
        priceDisplayedLbl.setText("Final Price");
        jPanel2.add(priceDisplayedLbl);
        priceDisplayedLbl.setBounds(120, 470, 130, 20);

        finalPriceLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        finalPriceLbl.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(finalPriceLbl);
        finalPriceLbl.setBounds(270, 470, 110, 20);

        destinationLbl.setBackground(new java.awt.Color(0, 204, 255));
        destinationLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        destinationLbl.setForeground(new java.awt.Color(255, 255, 255));
        destinationLbl.setText("Destination:");
        jPanel2.add(destinationLbl);
        destinationLbl.setBounds(110, 80, 80, 19);

        flightTypeLbl.setBackground(new java.awt.Color(0, 204, 255));
        flightTypeLbl.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        flightTypeLbl.setForeground(new java.awt.Color(255, 255, 255));
        flightTypeLbl.setText("Flight Type:");
        jPanel2.add(flightTypeLbl);
        flightTypeLbl.setBounds(110, 120, 79, 21);

        destinationCB.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        destinationCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "London", "Paris", "Madrid", "Berlin", "Lisbon" }));
        destinationCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinationCBActionPerformed(evt);
            }
        });
        jPanel2.add(destinationCB);
        destinationCB.setBounds(230, 80, 120, 26);

        movieCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
        movieCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movieCBActionPerformed(evt);
            }
        });
        jPanel2.add(movieCB);
        movieCB.setBounds(180, 260, 56, 20);

        entCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
        entCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entCBActionPerformed(evt);
            }
        });
        jPanel2.add(entCB);
        entCB.setBounds(472, 270, 60, 20);

        wifiCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
        jPanel2.add(wifiCB);
        wifiCB.setBounds(182, 320, 50, 20);

        massageCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Yes", "No" }));
        jPanel2.add(massageCB);
        massageCB.setBounds(472, 330, 60, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 550, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticketTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketTypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketTypeCBActionPerformed

    private void priceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceBtnActionPerformed
        // TODO add your handling code here:
        // Jake
        priceDisplayedLbl.setVisible(true);
        finalPriceLbl.setVisible(true);

        //Ryanair
        if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 400;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 500;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 150;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 200;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 325;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 400;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 450;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 500;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 375;
        } else if (airlineCB.getSelectedItem().equals("Ryanair") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 450;
        }
        //aer lingus
        else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 375;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 450;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 175;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 220;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 300;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 350;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 400;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 475;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 350;
        } else if (airlineCB.getSelectedItem().equals("Aer Lingus") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 450;
        } 
        //Virgin Atlantic
        else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 300;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 350;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 200;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 220;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 330;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 350;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 500;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 600;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 400;
        } else if (airlineCB.getSelectedItem().equals("Virgin Atlantic") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 475;
        } 
        //CityJet
        else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 325;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Paris")) {
            mainPrice = 375;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 225;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("London")) {
            mainPrice = 300;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 350;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Madrid")) {
            mainPrice = 400;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 425;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Berlin")) {
            mainPrice = 500;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Plane") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 350;
        } else if (airlineCB.getSelectedItem().equals("CityJet") && flightTypeCB.getSelectedItem().equals("Jet") && destinationCB.getSelectedItem().equals("Lisbon")) {
            mainPrice = 400;
        }
        else {
            mainPrice = 0;
        }
        //sec price
        //on all plane flights movie=15 wifi=20 coach=0 firstclass=75
        if (ticketTypeCB.getSelectedItem().equals("First Class") && movieCB.getSelectedItem().equals("Yes") && wifiCB.getSelectedItem().equals("Yes")) {
            secPPrice = 110;
        }else if (ticketTypeCB.getSelectedItem().equals("First Class") && movieCB.getSelectedItem().equals("No") && wifiCB.getSelectedItem().equals("Yes")){
            secPPrice = 95;
        } else if (ticketTypeCB.getSelectedItem().equals("First Class") && movieCB.getSelectedItem().equals("Yes") && wifiCB.getSelectedItem().equals("No")){
            secPPrice = 90;
        } else if (ticketTypeCB.getSelectedItem().equals("First Class") && movieCB.getSelectedItem().equals("No") && wifiCB.getSelectedItem().equals("No")){
            secPPrice = 75;
        }
        //Coach
        else if (ticketTypeCB.getSelectedItem().equals("Coach") && movieCB.getSelectedItem().equals("Yes") && wifiCB.getSelectedItem().equals("Yes")){
            secPPrice = 35;
        }else if (ticketTypeCB.getSelectedItem().equals("Coach") && movieCB.getSelectedItem().equals("No") && wifiCB.getSelectedItem().equals("Yes")){
            secPPrice = 20;
        } else if (ticketTypeCB.getSelectedItem().equals("Coach") && movieCB.getSelectedItem().equals("Yes") && wifiCB.getSelectedItem().equals("No")){
            secPPrice = 15;
        } else if (ticketTypeCB.getSelectedItem().equals("Coach") && movieCB.getSelectedItem().equals("No") && wifiCB.getSelectedItem().equals("No")){
            secPPrice = 0;
        } else {
            secPPrice = 0;
        }
         // Jet sec Premium= 100 Standard=0 ent=50 message=70
        //premium
        if (packageDealCB.getSelectedItem().equals("Premium") && entCB.getSelectedItem().equals("Yes") && massageCB.getSelectedItem().equals("Yes")){
            secJPrice=220;
        } else if (packageDealCB.getSelectedItem().equals("Premium") && entCB.getSelectedItem().equals("No") && massageCB.getSelectedItem().equals("Yes")){
            secJPrice=170;
        } else if (packageDealCB.getSelectedItem().equals("Premium") && entCB.getSelectedItem().equals("Yes") && massageCB.getSelectedItem().equals("No")){
            secJPrice=150;
        } else if (packageDealCB.getSelectedItem().equals("Premium") && entCB.getSelectedItem().equals("No") && massageCB.getSelectedItem().equals("No")){
            secJPrice=100;
        }
        //standard
        else if (packageDealCB.getSelectedItem().equals("Standard") && entCB.getSelectedItem().equals("Yes") && massageCB.getSelectedItem().equals("Yes")){
            secJPrice=120;
        } else if(packageDealCB.getSelectedItem().equals("Standard") && entCB.getSelectedItem().equals("Yes") && massageCB.getSelectedItem().equals("No")){
            secJPrice=50;
        } else if(packageDealCB.getSelectedItem().equals("Standard") && entCB.getSelectedItem().equals("No") && massageCB.getSelectedItem().equals("Yes")){
            secJPrice=70;
        } else if(packageDealCB.getSelectedItem().equals("Standard") && entCB.getSelectedItem().equals("No") && massageCB.getSelectedItem().equals("No")){
            secJPrice=0;
        } else{
            secJPrice=0;
        }
        //calculations
        finalPrice=mainPrice+secPPrice+secJPrice;    
        finalPriceLbl.setText("€"+finalPrice);
    }//GEN-LAST:event_priceBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        // TODO add your handling code here:
        //Lauren
        String output = p.printDetails();
        JOptionPane.showMessageDialog(null, output);
        
        JOptionPane.showMessageDialog(null, p.printDetails());
    }//GEN-LAST:event_displayBtnActionPerformed

    // Jake Horner
    private void clearFormBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormBtnActionPerformed
        // TODO add your handling code here:
        //Referenced from ...

        airlineCB.setSelectedIndex(-1);
        destinationCB.setSelectedIndex(-1);
        flightTypeCB.setSelectedIndex(-1);
        ticketTypeCB.setSelectedIndex(-1);
        movieBG.clearSelection();
        wifiBG.clearSelection();
        packageDealCB.setSelectedIndex(-1);
        entertainmentBG.clearSelection();
        massageBG.clearSelection();

        planeLbl.setVisible(false);
        ticketTypeLbl.setVisible(false);
        ticketTypeCB.setVisible(false);
        moviesLbl.setVisible(false);
        movieCB.setVisible(false);
        wifiLbl.setVisible(false);
        wifiCB.setVisible(false);
   

        jetLbl.setVisible(false);
        packageDealLbl.setVisible(false);
        packageDealCB.setVisible(false);
        entertainmentLbl.setVisible(false);
        entCB.setVisible(false);        
        massageLbl.setVisible(false);
        massageCB.setVisible(false);
        //finalPrice="";
    }//GEN-LAST:event_clearFormBtnActionPerformed

    //Lauren
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        //Lauren
        //Referenced from EmployeeApplication made in class

    }//GEN-LAST:event_addBtnActionPerformed

    private void flightTypeCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightTypeCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightTypeCBActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        //Lauren

        if (flightTypeCB.getSelectedItem().equals("Plane")) {
            planeLbl.setVisible(true);
            ticketTypeLbl.setVisible(true);
            ticketTypeCB.setVisible(true);
            moviesLbl.setVisible(true);
            movieCB.setVisible(true);
            wifiLbl.setVisible(true);
            wifiCB.setVisible(true);

            jetLbl.setVisible(false);
            packageDealLbl.setVisible(false);
            packageDealCB.setVisible(false);
            entertainmentLbl.setVisible(false);
            entCB.setVisible(false);
            massageLbl.setVisible(false);
            massageCB.setVisible(false);
            log = new Plane[100];
            size = 0;
            
        }
        
        else if (flightTypeCB.getSelectedItem().equals("Jet")) {
            jetLbl.setVisible(true);
            packageDealLbl.setVisible(true);
            packageDealCB.setVisible(true);
            entertainmentLbl.setVisible(true);
            entCB.setVisible(true);
            massageLbl.setVisible(true);
            massageCB.setVisible(true);

            planeLbl.setVisible(false);
            ticketTypeLbl.setVisible(false);
            ticketTypeCB.setVisible(false);
            moviesLbl.setVisible(false);
            movieCB.setVisible(false);
            wifiLbl.setVisible(false);
            wifiCB.setVisible(false);
        } 
        
        else {
            planeLbl.setVisible(false);
            ticketTypeLbl.setVisible(false);
            ticketTypeCB.setVisible(false);
            moviesLbl.setVisible(false);
            movieCB.setVisible(false);
            wifiLbl.setVisible(false);
            wifiCB.setVisible(false);
            jetLbl.setVisible(false);
            packageDealLbl.setVisible(false);
            packageDealCB.setVisible(false);
            entertainmentLbl.setVisible(false);
            entCB.setVisible(false);
            massageLbl.setVisible(false);
            massageCB.setVisible(false);
            airlineCB.setSelectedIndex(-1);
            destinationCB.setSelectedIndex(-1);
            flightTypeCB.setSelectedIndex(-1);
            ticketTypeCB.setSelectedIndex(-1);
            movieBG.clearSelection();
            wifiBG.clearSelection();
            packageDealCB.setSelectedIndex(-1);
            entertainmentBG.clearSelection();
            massageBG.clearSelection();
        }

    }//GEN-LAST:event_searchBtnActionPerformed

    private void jPanel2ComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jPanel2ComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2ComponentRemoved

    private void airlineCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineCBActionPerformed

    private void destinationCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinationCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinationCBActionPerformed

    private void movieCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movieCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movieCBActionPerformed

    private void entCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlightGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlightGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> airlineCB;
    private javax.swing.JLabel airlineLbl;
    private javax.swing.JButton clearFormBtn;
    private javax.swing.JComboBox<String> destinationCB;
    private javax.swing.JLabel destinationLbl;
    private javax.swing.JButton displayBtn;
    private javax.swing.JComboBox<String> entCB;
    private javax.swing.ButtonGroup entertainmentBG;
    private javax.swing.JLabel entertainmentLbl;
    private javax.swing.JLabel finalPriceLbl;
    private javax.swing.JComboBox<String> flightTypeCB;
    private javax.swing.JLabel flightTypeLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jetLbl;
    private javax.swing.ButtonGroup massageBG;
    private javax.swing.JComboBox<String> massageCB;
    private javax.swing.JLabel massageLbl;
    private javax.swing.ButtonGroup movieBG;
    private javax.swing.JComboBox<String> movieCB;
    private javax.swing.JLabel moviesLbl;
    private javax.swing.JComboBox<String> packageDealCB;
    private javax.swing.JLabel packageDealLbl;
    private javax.swing.JLabel planeLbl;
    private javax.swing.JButton priceBtn;
    private javax.swing.JLabel priceDisplayedLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> ticketTypeCB;
    private javax.swing.JLabel ticketTypeLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.ButtonGroup wifiBG;
    private javax.swing.JComboBox<String> wifiCB;
    private javax.swing.JLabel wifiLbl;
    // End of variables declaration//GEN-END:variables

    //Connor
    private void ReadFile() {
        try{
            File f = new File("Output.data");
            FileInputStream fStream = new FileInputStream(f);
            ObjectInputStream oStream = new ObjectInputStream(fStream);
            
            log = (Plane[]) oStream.readObject();
            oStream.close();
        }
        catch(IOException | ClassNotFoundException ex){
            System.out.println(ex);
        }
    }

  
}
